export const adminText: string
export const avatarContainer: string
export const commentText: string
export const email: string
export const longValue: string
export const mentionedUser: string
export const mentions: string
export const mentionsControl: string
export const mentionsHighlighter: string
export const mentionsInput: string
export const mentionsMention: string
export const mentionsMultiLine: string
export const mentionsSingleLine: string
export const mentionsSuggestionsItem: string
export const mentionsSuggestionsItemFocused: string
export const mentionsSuggestionsList: string
export const noResultsMessage: string
export const slackLogo: string
export const slackLogoContainer: string
export const suggestionContainer: string
export const suggestionHeader: string
